version: '2'
services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
  webhooks:
    build: .
    command: yarn run dev 
    ports:
      - "7777:7777"
    user: "11111112"
    links:
      - rabbitmq:3-management
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
