apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-secret-environment-template
parameters:
  - name: JWTSECRET
    description: JSON Web Token generation secret
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: RABBITMQ_PASSWORD
    description: Password to connect to rabbitmq to
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_SITEGROUP
    description: Which sitegroup this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: PROJECT
    description: Name of the Project that this service is in
    required: true
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: jwtsecret
  stringData:
    JWTSECRET: ${JWTSECRET}
- kind: Secret
  apiVersion: v1
  metadata:
    name: rabbitmq-password
  stringData:
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
- kind: Secret
  apiVersion: v1
  metadata:
    name: rabbitmq-username
  stringData:
    RABBITMQ_USERNAME: lagoon