
name: lagoon
root: .

windows:
  - logs:
      layout: tiled
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - docker-compose logs -f --tail=5 webhook-handler
        - docker-compose logs -f --tail=5 webhooks2tasks
        - docker-compose logs -f --tail=5 openshiftdeploy
        - docker-compose logs -f --tail=5 openshiftremove
