site_name: Lagoon

pages:
- Home: index.md
- Using Lagoon: using_lagoon/index.md
- Administration:
  - Administering Lagoon: administering_lagoon/index.md
- Development:
  - Developing Lagoon: developing_lagoon/index.md
  - Tests: developing_lagoon/tests.md
  - Contributing: developing_lagoon/contributing.md
- Code Of Conduct: code_of_conduct.md
theme: readthedocs
