apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-secret-environment-template
parameters:
  - name: JWTSECRET
    description: JSON Web Token generation secret
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: RABBITMQ_PASSWORD
    description: Password to connect to rabbitmq to
    generate: expression
    from: "[a-zA-Z0-9]{32}"
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: secret-environment
  stringData:
    JWTSECRET: ${JWTSECRET}
    RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    RABBITMQ_USERNAME: lagoon