apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeioservice-template
parameters:
  - name: TAG
    description: Which tag should be deployed
    required: true
  - name: NAME
    description: How is the resources are called
    required: true
  - name: SHORT_NAME
    description: Name of resources in max 24 chars
    required: true
  - name: SITEGROUP
    description: Name of the site group
    required: true
  - name: OPENSHIFT_PROJECT
    description: Name of the openshift project we are created in
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    revisionHistoryLimit: 2
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: ${OPENSHIFT_PROJECT}/${SITEGROUP}:${TAG}
          name: ${NAME}
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1000m -Xmx1000m"
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            limits:
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 300Mi
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: ${NAME}-data-volume
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 120
        volumes:
        - name: ${NAME}-data-volume
          emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${SITEGROUP}:${TAG}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${SHORT_NAME}
  spec:
    ports:
    - name: 9200-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
  status:
    loadBalancer: {}