apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${AMAZEEIO_SERVICE}-template
parameters:
  - name: BRANCH
    description: Which branch (also docker image tag) should be deployed
    required: true
  - name: RABBITMQ_HOST
    description: Hostname of the RabbitMQ Server to connect to
    required: true
  - name: AMAZEEIO_SERVICE
    description: How is this service called
    required: true
  - name: OPENSHIFT_PROJECT
    description: Name of the openshift project we are created in
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
    name: ${AMAZEEIO_SERVICE}-${BRANCH}
  spec:
    replicas: 1
    selector:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
      deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
    revisionHistoryLimit: 2
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${AMAZEEIO_SERVICE}-${BRANCH}
          deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
      spec:
        containers:
        - image: ${OPENSHIFT_PROJECT}/${AMAZEEIO_SERVICE}:${BRANCH}
          name: ${AMAZEEIO_SERVICE}-${BRANCH}
          env:
          - name: RABBITMQ_HOST
            value: ${RABBITMQ_HOST}
          - name: NODE_ENV
            value: production
          ports:
          - containerPort: 7777
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 3
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 250m
              memory: 250Mi
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${AMAZEEIO_SERVICE}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${AMAZEEIO_SERVICE}:${BRANCH}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
    name: ${AMAZEEIO_SERVICE}-${BRANCH}
  spec:
    ports:
    - name: 7777-tcp
      port: 80
      protocol: TCP
      targetPort: 7777
    selector:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
      deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
  status:
    loadBalancer: {}
## ## No route for production right now, until https://ticket.vshn.net/browse/AMZE-329 is figured out
##- apiVersion: v1
##  kind: Route
##  metadata:
##    creationTimestamp: null
##    labels:
##      app: ${AMAZEEIO_SERVICE}-${BRANCH}
##    name: ${AMAZEEIO_SERVICE}-${BRANCH}-io
##  spec:
##    host: hooks.amazeeio.cloud
##    port:
##      targetPort: 7777-tcp
##    to:
##      kind: Service
##      name: ${AMAZEEIO_SERVICE}-${BRANCH}
##- apiVersion: v1
##  kind: Route
##  metadata:
##    creationTimestamp: null
##    labels:
##      app: ${AMAZEEIO_SERVICE}-${BRANCH}
##    name: ${AMAZEEIO_SERVICE}-${BRANCH}-cloud
##  spec:
##    host: hooks.amazee.io
##    port:
##      targetPort: 7777-tcp
##    to:
##      kind: Service
##      name: ${AMAZEEIO_SERVICE}-${BRANCH}
