apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template-node
parameters:
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_SITEGROUP
    description: Which sitegroup this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: ROUTER_URL
    description: URL of the Router
    required: true
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: amazeeio-env
  data:
    AMAZEEIO_GIT_SAFE_BRANCH: ${SAFE_BRANCH}
    AMAZEEIO_GIT_BRANCH: ${BRANCH}
    AMAZEEIO_SAFE_SITEGROUP: ${SAFE_SITEGROUP}
    AMAZEEIO_GIT_SHA: ${AMAZEEIO_GIT_SHA}
    AMAZEEIO_SITEGROUP: ${SITEGROUP}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: app
  spec:
    replicas: 1
    selector:
      app: nodejs
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nodejs
          branch: ${SAFE_BRANCH}
          sitegroup: ${SAFE_SITEGROUP}
      spec:
        containers:
        - image: ' '
          name: nodejs
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: AMAZEEIO_GIT_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_BRANCH
            - name: AMAZEEIO_GIT_SAFE_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SAFE_BRANCH
            - name: AMAZEEIO_GIT_SHA
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SHA
            - name: AMAZEEIO_SITEGROUP
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_SITEGROUP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs
        from:
          kind: ImageStreamTag
          name: app:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: nodejs
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: nodejs
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: nodejs
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: nodejs
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: nodejs
  spec:
    host: ${ROUTER_URL}
    port:
      targetPort: 3000-tcp
    to:
      kind: Service
      name: nodejs