apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${AMAZEEIO_SERVICE}-template
parameters:
  - name: BRANCH
    description: Which branch (also docker image tag) should be deployed
    required: true
  - name: AMAZEEIO_SERVICE
    description: How is this service called
    required: true
  - name: OPENSHIFT_PROJECT
    description: Name of the openshift project we are created in
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
    name: ${AMAZEEIO_SERVICE}-${BRANCH}
  spec:
    replicas: 1
    selector:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
      deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
    revisionHistoryLimit: 2
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${AMAZEEIO_SERVICE}-${BRANCH}
          deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
      spec:
        containers:
        - image: ${OPENSHIFT_PROJECT}/${AMAZEEIO_SERVICE}:${BRANCH}
          name: ${AMAZEEIO_SERVICE}-${BRANCH}
          env:
          - name: ADMIN_PASSWORD
            value: fZk3bf7hsbZCQ4kYHeYkXYNitCoy6u3BbmZrm9FR
          - name: JENKINS_SLAVE_AGENT_PORT
            value: '31241'
          - name: JAVA_OPTS
            value: '-Djenkins.install.runSetupWizard=false -Xmx1800m'
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 31236
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            timeoutSeconds: 3
            failureThreshold: 30
          resources:
            limits:
              memory: 2000Mi
            requests:
              memory: 2000Mi
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: ${AMAZEEIO_SERVICE}-${BRANCH}-volume
        volumes:
        - name: ${AMAZEEIO_SERVICE}-${BRANCH}-volume
          persistentVolumeClaim:
            claimName: ${AMAZEEIO_SERVICE}-${BRANCH}-volume
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${AMAZEEIO_SERVICE}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${AMAZEEIO_SERVICE}:${BRANCH}
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${AMAZEEIO_SERVICE}-${BRANCH}-volume
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
    name: ${AMAZEEIO_SERVICE}-${BRANCH}
  spec:
    ports:
    - name: 8080-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
      deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
    name: ${AMAZEEIO_SERVICE}-${BRANCH}-jnlp2
  spec:
    ports:
    - name: jnlp2
      port: 31241
      protocol: TCP
      targetPort: 31241
      nodePort: 31241
    type: LoadBalancer
    externalIPs: []
    selector:
      app: ${AMAZEEIO_SERVICE}-${BRANCH}
      deploymentconfig: ${AMAZEEIO_SERVICE}-${BRANCH}
  status:
    loadBalancer: {}
## ## No route for production right now, until https://ticket.vshn.net/browse/AMZE-329 is figured out
##- apiVersion: v1
##  kind: Route
##  metadata:
##    creationTimestamp: null
##    labels:
##      app: ${AMAZEEIO_SERVICE}-${BRANCH}
##    name: ${AMAZEEIO_SERVICE}-${BRANCH}
##  spec:
##    host: jenkins.amazeeio.cloud
##    port:
##      targetPort: 8080-tcp
##    to:
##      kind: Service
##      name: ${AMAZEEIO_SERVICE}-${BRANCH}